import type {
  ListingResponse,
  WishlistResponse,
  OrderResponse,
  DonationResponse,
  LostAndFoundResponse,
  ReviewResponse,
  ReviewStats,
} from "../../../services/listingService";
import type { PaginatedResponse } from "../../../types/api";

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const MOCK_LISTINGS: ListingResponse[] = [
  {
    id: 1,
    title: "Homemade Hyderabadi Biryani – Sunday Special",
    description: "Authentic dum biryani made with basmati rice, tender chicken, and secret family spices. Serves 2-3 people. Order before Saturday 8 PM for Sunday delivery within the community.",
    price: 350,
    priceUnit: "portion",
    category: "Homemade Food",
    status: "ACTIVE",
    transactionMode: "CHAT_ONLY",
    visibility: "COMMUNITY",
    location: "Tower A, Apt 302",
    imageUrls: [],
    seller: { id: 101, fullName: "Priya Sharma", verified: true },
    communityId: 1,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 2,
    title: "iPhone 14 Pro – 128GB Space Black",
    description: "Gently used iPhone 14 Pro in excellent condition. Battery health 94%. Comes with original charger, box, and a clear case. No scratches on screen or body.",
    price: 52000,
    priceUnit: "",
    category: "Electronics",
    status: "ACTIVE",
    transactionMode: "CHAT_CALL",
    visibility: "COMMUNITY",
    location: "Tower C, Apt 1201",
    imageUrls: [],
    seller: { id: 102, fullName: "Rahul Menon", verified: true },
    communityId: 1,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 3,
    title: "Honda Activa 6G – 2022 Model",
    description: "Single owner, only 8,000 km driven. All service records available. Insurance valid till March 2027. White color, excellent mileage.",
    price: 72000,
    priceUnit: "",
    category: "Vehicles",
    status: "ACTIVE",
    transactionMode: "CHAT_CALL",
    visibility: "COMMUNITY",
    location: "Parking B2, Slot 45",
    imageUrls: [],
    seller: { id: 103, fullName: "Amit Patel", verified: false },
    communityId: 1,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 4,
    title: "2BHK Available for Rent – Tower D",
    description: "Fully furnished 2BHK with AC in both rooms, modular kitchen, washing machine, and fridge. East facing with garden view. Available from August 1st.",
    price: 28000,
    priceUnit: "month",
    category: "Real Estate",
    status: "ACTIVE",
    transactionMode: "CHAT_CALL",
    visibility: "COMMUNITY",
    location: "Tower D, Floor 8",
    imageUrls: [],
    seller: { id: 104, fullName: "Sunita Reddy", verified: true },
    communityId: 1,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 5,
    title: "Yoga & Meditation Classes – Morning Batch",
    description: "Certified yoga instructor offering morning batch (6-7 AM) at the community hall. Hatha and Vinyasa styles. First class free! Monthly packages available.",
    price: 2000,
    priceUnit: "month",
    category: "Services",
    status: "ACTIVE",
    transactionMode: "CHAT_ONLY",
    visibility: "COMMUNITY",
    location: "Community Hall, Ground Floor",
    imageUrls: [],
    seller: { id: 105, fullName: "Deepa Nair", verified: true },
    communityId: 1,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 6,
    title: "Samsung 55\" Crystal 4K Smart TV",
    description: "2023 model, barely used for 6 months. Moving abroad, selling at a great price. Remote, stand, and wall mount bracket included. Crystal clear picture quality.",
    price: 32000,
    priceUnit: "",
    category: "Electronics",
    status: "ACTIVE",
    transactionMode: "CHAT_ONLY",
    visibility: "COMMUNITY",
    location: "Tower B, Apt 605",
    imageUrls: [],
    seller: { id: 106, fullName: "Karthik Iyer", verified: true },
    communityId: 1,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
];

export const MOCK_WISHLIST: WishlistResponse[] = [
  {
    id: 1,
    listingId: 2,
    listingTitle: "iPhone 14 Pro – 128GB Space Black",
    listingPrice: 52000,
    listingCategory: "Electronics",
    listingStatus: "ACTIVE",
    listingImageUrl: null,
    sellerName: "Rahul Menon",
    addedAt: daysAgo(1),
  },
  {
    id: 2,
    listingId: 5,
    listingTitle: "Yoga & Meditation Classes – Morning Batch",
    listingPrice: 2000,
    listingCategory: "Services",
    listingStatus: "ACTIVE",
    listingImageUrl: null,
    sellerName: "Deepa Nair",
    addedAt: daysAgo(3),
  },
];

export const MOCK_ORDERS: OrderResponse[] = [
  {
    id: 1,
    orderNumber: "ORD-20260718-001",
    buyer: { id: 100, fullName: "Demo User" },
    seller: { id: 101, fullName: "Priya Sharma", verified: true },
    status: "CONFIRMED",
    totalAmount: 700,
    notes: "Extra spicy please",
    deliveryAddress: "Tower B, Apt 401",
    items: [
      { id: 1, listingId: 1, listingTitle: "Homemade Hyderabadi Biryani – Sunday Special", quantity: 2, unitPrice: 350, imageUrl: null },
    ],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 2,
    orderNumber: "ORD-20260715-002",
    buyer: { id: 100, fullName: "Demo User" },
    seller: { id: 106, fullName: "Karthik Iyer", verified: true },
    status: "PENDING",
    totalAmount: 32000,
    notes: "",
    deliveryAddress: "Tower B, Apt 401",
    items: [
      { id: 2, listingId: 6, listingTitle: "Samsung 55\" Crystal 4K Smart TV", quantity: 1, unitPrice: 32000, imageUrl: null },
    ],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 3,
    orderNumber: "ORD-20260710-003",
    buyer: { id: 107, fullName: "Meera Joshi" },
    seller: { id: 100, fullName: "Demo User", verified: true },
    status: "DELIVERED",
    totalAmount: 350,
    notes: "",
    deliveryAddress: "Tower C, Apt 901",
    items: [
      { id: 3, listingId: 1, listingTitle: "Homemade Hyderabadi Biryani – Sunday Special", quantity: 1, unitPrice: 350, imageUrl: null },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
];

export const MOCK_DONATIONS: DonationResponse[] = [
  {
    id: 1,
    title: "Children's Story Books Collection",
    description: "Set of 15 story books for ages 5-10. Includes Panchatantra, Amar Chitra Katha, and Enid Blyton. Good condition, some mild wear.",
    category: "Books",
    condition: "GOOD",
    status: "AVAILABLE",
    imageUrl: null,
    donor: { id: 104, fullName: "Sunita Reddy" },
    communityId: 1,
    claimedByName: null,
    createdAt: daysAgo(3),
  },
  {
    id: 2,
    title: "Baby Walker – Barely Used",
    description: "Bright Starts baby walker in excellent condition. Used for only 2 months. Clean and sanitized. Suitable for 6-12 months.",
    category: "Toys",
    condition: "LIKE_NEW",
    status: "AVAILABLE",
    imageUrl: null,
    donor: { id: 105, fullName: "Deepa Nair" },
    communityId: 1,
    claimedByName: null,
    createdAt: daysAgo(5),
  },
  {
    id: 3,
    title: "Winter Jackets – Men's Size L",
    description: "Two warm winter jackets. One black puffer, one navy fleece. Both in good condition. Giving away as I've lost weight.",
    category: "Clothing",
    condition: "GOOD",
    status: "CLAIMED",
    imageUrl: null,
    donor: { id: 103, fullName: "Amit Patel" },
    communityId: 1,
    claimedByName: "Ravi Kumar",
    createdAt: daysAgo(8),
  },
  {
    id: 4,
    title: "Microwave Oven – Samsung 28L",
    description: "Working microwave oven. Bought a new one, so giving this away. Convection mode has minor issues, but grill and micro modes work perfectly.",
    category: "Kitchen",
    condition: "FAIR",
    status: "AVAILABLE",
    imageUrl: null,
    donor: { id: 102, fullName: "Rahul Menon" },
    communityId: 1,
    claimedByName: null,
    createdAt: daysAgo(2),
  },
];

export const MOCK_LOST_AND_FOUND: LostAndFoundResponse[] = [
  {
    id: 1,
    title: "Blue Leather Wallet",
    description: "Lost my blue leather wallet near the parking area. Contains Aadhaar card, PAN card, and some cash. Please contact if found.",
    type: "LOST",
    category: "Personal Items",
    imageUrl: null,
    location: "Parking Area B2",
    dateOccurred: "2026-07-18",
    status: "OPEN",
    reporter: { id: 103, fullName: "Amit Patel" },
    communityId: 1,
    createdAt: daysAgo(1),
  },
  {
    id: 2,
    title: "Set of House Keys with Red Keychain",
    description: "Found a set of 3 keys with a red keychain near the children's play area. Left at the security desk.",
    type: "FOUND",
    category: "Keys",
    imageUrl: null,
    location: "Children's Play Area",
    dateOccurred: "2026-07-17",
    status: "OPEN",
    reporter: { id: 104, fullName: "Sunita Reddy" },
    communityId: 1,
    createdAt: daysAgo(2),
  },
  {
    id: 3,
    title: "Golden Retriever – Name: Bruno",
    description: "Our pet Golden Retriever Bruno went missing from Tower A vicinity. He's friendly, wears a blue collar with name tag. Please call if spotted.",
    type: "LOST",
    category: "Pets",
    imageUrl: null,
    location: "Tower A Garden Area",
    dateOccurred: "2026-07-16",
    status: "OPEN",
    reporter: { id: 101, fullName: "Priya Sharma" },
    communityId: 1,
    createdAt: daysAgo(3),
  },
  {
    id: 4,
    title: "Child's Water Bottle – Blue Chhota Bheem",
    description: "Found a children's water bottle near the swimming pool. Blue colored with Chhota Bheem stickers. Kept at the pool reception.",
    type: "FOUND",
    category: "Personal Items",
    imageUrl: null,
    location: "Swimming Pool",
    dateOccurred: "2026-07-19",
    status: "RESOLVED",
    reporter: { id: 106, fullName: "Karthik Iyer" },
    communityId: 1,
    createdAt: daysAgo(1),
  },
];

export const MOCK_REVIEWS: ReviewResponse[] = [
  {
    id: 1,
    listingId: 1,
    listingTitle: "Homemade Hyderabadi Biryani",
    reviewer: { id: 107, fullName: "Meera Joshi", verified: true },
    rating: 5,
    comment: "Absolutely delicious! The biryani was perfectly spiced and the portion size was generous. Will definitely order again.",
    sellerReply: "Thank you so much, Meera! Glad you enjoyed it. Try the mutton biryani next time!",
    createdAt: daysAgo(4),
  },
  {
    id: 2,
    listingId: 1,
    listingTitle: "Homemade Hyderabadi Biryani",
    reviewer: { id: 108, fullName: "Vikram Singh", verified: false },
    rating: 4,
    comment: "Very tasty biryani. Rice was perfectly cooked. Could use a bit more chicken though.",
    sellerReply: null,
    createdAt: daysAgo(6),
  },
  {
    id: 3,
    listingId: 1,
    listingTitle: "Homemade Hyderabadi Biryani",
    reviewer: { id: 109, fullName: "Ananya Gupta", verified: true },
    rating: 5,
    comment: "Best homemade biryani I've had in this city! Fresh ingredients and amazing flavor.",
    sellerReply: null,
    createdAt: daysAgo(10),
  },
];

export const MOCK_REVIEW_STATS: ReviewStats = {
  averageRating: 4.7,
  totalReviews: 3,
};

export const MOCK_MY_LISTINGS: ListingResponse[] = [
  { ...MOCK_LISTINGS[0], seller: { id: 100, fullName: "Demo User", verified: true } },
  {
    id: 7,
    title: "Homemade Mango Pickle – 500g Jar",
    description: "Traditional Andhra-style mango pickle made with fresh raw mangoes. No preservatives, pure mustard oil.",
    price: 250,
    priceUnit: "jar",
    category: "Homemade Food",
    status: "PAUSED",
    transactionMode: "CHAT_ONLY",
    visibility: "COMMUNITY",
    location: "Tower A, Apt 302",
    imageUrls: [],
    seller: { id: 100, fullName: "Demo User", verified: true },
    communityId: 1,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: 8,
    title: "Study Table with Chair – IKEA",
    description: "Compact IKEA study desk with ergonomic chair. Perfect for WFH setup. Minor scratches on the table surface.",
    price: 4500,
    priceUnit: "",
    category: "Electronics",
    status: "SOLD",
    transactionMode: "CHAT_ONLY",
    visibility: "COMMUNITY",
    location: "Tower A, Apt 302",
    imageUrls: [],
    seller: { id: 100, fullName: "Demo User", verified: true },
    communityId: 1,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(12),
  },
];

export function paginate<T>(items: T[], page: number, size: number): PaginatedResponse<T> {
  const start = page * size;
  const content = items.slice(start, start + size);
  const totalPages = Math.ceil(items.length / size);
  return {
    content,
    totalElements: items.length,
    totalPages,
    number: page,
    size,
    first: page === 0,
    last: page >= totalPages - 1,
  };
}

export const USE_MOCK_DATA = true;
