import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity,
  Archive,
  ArrowLeft,
  BarChart3,
  CalendarClock,
  Check,
  CheckCircle2,
  Clock3,
  Copy,
  Download,
  Eye,
  FolderOpen,
  History,
  Image as ImageIcon,
  Layers,
  LockKeyhole,
  Mail,
  PaintBucket,
  Plus,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Square,
  SquareCheck,
  TestTube2,
  Trash2,
  Upload,
  Workflow,
} from "lucide-react";
import type { Editor } from "grapesjs";
import { useAuth } from "../../../contexts/AuthContext";
import { communityService } from "../../../services/communityService";
import { emailTemplateService, type EmailTemplateRecord, type EmailTemplateStatus } from "../../../services/emailTemplateService";
import type { CommunityResponse } from "../../../types/api";
import { showError, showSuccess, showWarning } from "../../../utils/ToastUtils";
import { BuilderCanvas } from "./emailbuilder/BuilderCanvas";
import { ComponentPalette } from "./emailbuilder/ComponentPalette";
import { PropertyPanel } from "./emailbuilder/PropertyPanel";
import { Toolbar } from "./emailbuilder/Toolbar";
import { PreviewModal, type PreviewDevice, type PreviewTheme } from "./emailbuilder/PreviewModal";
import { ThemeBuilder } from "./emailbuilder/ThemeBuilder";
import { themePersistenceService, type EmailThemeRecord } from "./emailbuilder/themePersistenceService";
import { DEFAULT_THEME, generateCss, type ThemeSettings } from "./emailbuilder/themeEngine";
import {
  analyticsMetrics,
  approvalSteps,
  auditEvents,
  communityThemeDefaults,
  conditionalRules,
  dynamicFieldGroups,
  emailBlocks,
  emailClients,
  emailTemplateCategories,
  imageLibraryAssets,
  permissionMatrix,
  repeatableCollections,
  sampleDatasets,
  starterTemplateCss,
  starterTemplateHtml,
  templateStarters,
} from "./emailbuilder/emailBuilderData";

type ViewMode = "manager" | "builder";
type PlatformSection = "templates" | "theme" | "blocks" | "assets" | "workflow" | "analytics" | "governance";

interface WorkingTemplate {
  id?: number;
  communityId: number;
  templateName: string;
  subject: string;
  html: string;
  css: string;
  jsonLayout: unknown;
  status: EmailTemplateStatus;
  category?: string;
  tags?: string[];
  themeName?: string;
  themeJson?: string;
  generatedCss?: string;
}

const GENERATED_THEME_START = "/* === Mana Applied Theme CSS START === */";
const GENERATED_THEME_END = "/* === Mana Applied Theme CSS END === */";
const LEGACY_GENERATED_THEME_MARKER = "/* === Generated by Mana Email Theme Engine === */";

const platformSections: Array<{ id: PlatformSection; label: string; icon: React.ElementType }> = [
  { id: "templates", label: "Templates", icon: Mail },
  { id: "theme", label: "Theme", icon: PaintBucket },
  { id: "blocks", label: "Blocks", icon: Layers },
  { id: "assets", label: "Assets", icon: ImageIcon },
  { id: "workflow", label: "Workflow", icon: Workflow },
  { id: "analytics", label: "Analytics", icon: BarChart3 },
  { id: "governance", label: "Governance", icon: ShieldCheck },
];

function toWorkingTemplate(template: EmailTemplateRecord, communityId: number): WorkingTemplate {
  return {
    id: template.id,
    communityId: template.communityId ?? communityId,
    templateName: template.name,
    subject: template.subject,
    html: template.html || starterTemplateHtml,
    css: template.css || starterTemplateCss,
    jsonLayout: template.jsonLayout ?? {},
    status: template.status,
    category: template.category ?? "Community",
    tags: template.tags ?? [],
    themeName: template.themeName,
    themeJson: template.themeJson,
    generatedCss: template.generatedCss,
  };
}

function createBlankTemplate(communityId: number, name = "Tournament Announcement", category = "Tournament"): WorkingTemplate {
  return {
    communityId,
    templateName: name,
    subject: `${name} - {{communityName}}`,
    html: starterTemplateHtml,
    css: starterTemplateCss,
    jsonLayout: {},
    status: "DRAFT",
    category,
    tags: [category.toLowerCase()],
    themeName: DEFAULT_THEME.themeName,
    themeJson: JSON.stringify(DEFAULT_THEME),
    generatedCss: generateCss(DEFAULT_THEME),
  };
}

function replaceMergeFields(html: string, values: Record<string, string | undefined>) {
  return html.replace(/\{\{(\w+)\}\}/g, (match, key) => values[key] ?? match);
}

function parseThemeRecord(record?: EmailThemeRecord): ThemeSettings | null {
  if (!record) return null;
  try {
    return JSON.parse(record.themeJson) as ThemeSettings;
  } catch {
    return null;
  }
}

function parseThemeJson(themeJson?: string): ThemeSettings | null {
  if (!themeJson) return null;
  try {
    return JSON.parse(themeJson) as ThemeSettings;
  } catch {
    return null;
  }
}

function stripAppliedThemeCss(css = "") {
  const start = css.indexOf(GENERATED_THEME_START);
  const end = css.indexOf(GENERATED_THEME_END);
  if (start === -1 || end === -1 || end < start) return css;
  return `${css.slice(0, start)}${css.slice(end + GENERATED_THEME_END.length)}`.trim();
}

function stripThemeCss(css = "") {
  const withoutAppliedTheme = stripAppliedThemeCss(css);
  return withoutAppliedTheme.includes(LEGACY_GENERATED_THEME_MARKER) ? "" : withoutAppliedTheme;
}

function buildTemplateCss(settings: ThemeSettings, existingCss = "") {
  const customCss = stripThemeCss(existingCss);
  const themeCss = `${GENERATED_THEME_START}\n${generateCss(settings)}\n${GENERATED_THEME_END}`;
  return customCss ? `${themeCss}\n\n${customCss}` : themeCss;
}

function upsertClassName(html: string, className: string) {
  const match = html.match(/class=(["'])(.*?)\1/i);
  if (!match) return html.replace(/^<([a-z][\w:-]*)(\s|>)/i, `<$1 class="${className}"$2`);
  const current = match[2].split(/\s+/).filter(Boolean);
  if (current.includes(className)) return html;
  return html.replace(match[0], `class=${match[1]}${[...current, className].join(" ")}${match[1]}`);
}

function normalizeTemplateHtmlForTheme(html: string, settings: ThemeSettings) {
  const source = (html || starterTemplateHtml).trim();
  if (source.includes('data-mana-theme="true"')) {
    return source
      .replace(/data-mana-theme-name=(["']).*?\1/i, `data-mana-theme-name="${settings.themeName}"`)
      .replace(/data-mana-theme-updated=(["']).*?\1/i, `data-mana-theme-updated="${new Date().toISOString()}"`);
  }

  const rootTableMatch = source.match(/<table\b[^>]*>/i);
  let themed = source;
  if (rootTableMatch) {
    let rootTable = rootTableMatch[0];
    rootTable = upsertClassName(rootTable, "email-container");
    if (!/data-mana-theme=/i.test(rootTable)) {
      rootTable = rootTable.replace(/>$/, ` data-mana-theme="true" data-mana-theme-name="${settings.themeName}" data-mana-theme-updated="${new Date().toISOString()}">`);
    }
    themed = source.replace(rootTableMatch[0], rootTable);
  }

  if (!/class=(["'])[^"']*\bemail-wrapper\b/i.test(themed)) {
    themed = `<div class="email-wrapper" data-mana-theme="true" data-mana-theme-name="${settings.themeName}" data-mana-theme-updated="${new Date().toISOString()}">\n${themed}\n</div>`;
  }

  return themed
    .replace(/<a\b(?![^>]*class=)/gi, '<a class="btn-primary"')
    .replace(/<td([^>]*?)style=(["'])(?=[^"']*background:\s*#0f766e)/i, '<td class="email-header"$1style=$2')
    .replace(/<td([^>]*?)style=(["'])(?=[^"']*padding:28px 32px)/i, '<td class="email-body"$1style=$2')
    .replace(/<td([^>]*?)style=(["'])(?=[^"']*background:\s*#f9fafb)/i, '<td class="email-footer"$1style=$2');
}

function buildAppliedThemeTemplate(template: WorkingTemplate, settings: ThemeSettings): WorkingTemplate {
  const generatedCss = generateCss(settings);
  return {
    ...template,
    html: normalizeTemplateHtmlForTheme(template.html, settings),
    css: buildTemplateCss(settings, template.css),
    themeName: settings.themeName,
    themeJson: JSON.stringify(settings),
    generatedCss,
  };
}

function themedPreviewDocument(html: string, css: string, settings: ThemeSettings, values: Record<string, string | undefined>) {
  const themedHtml = replaceMergeFields(normalizeTemplateHtmlForTheme(html || starterTemplateHtml, settings), values);
  return `
    <!doctype html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          ${buildTemplateCss(settings, css)}
          body { margin:0; background:${settings.backgroundColor}; color:${settings.textColor}; font-family:'${settings.bodyFont}',Arial,sans-serif; }
          body table[role="presentation"] { font-family:'${settings.bodyFont}',Arial,sans-serif !important; }
          body table[role="presentation"] table[role="presentation"] { max-width:${settings.containerWidth}px !important; }
          body td[style*="background:#0f766e"],
          body td[style*="background:#0f172a"],
          body td[style*="background: #0f766e"],
          body td[style*="background: #0f172a"] { background:${settings.primaryColor} !important; color:#ffffff !important; }
          body h1 { font-family:'${settings.headingFont}',Arial,sans-serif !important; font-size:${settings.headingSize}px !important; }
          body h2 { font-family:'${settings.headingFont}',Arial,sans-serif !important; color:${settings.textColor} !important; }
          body a { background:${settings.buttonStyle === "gradient" ? `linear-gradient(135deg,${settings.primaryColor},${settings.accentColor})` : settings.primaryColor} !important; color:${settings.buttonTextColor} !important; border-radius:${settings.buttonRadius}px !important; }
        </style>
      </head>
      <body>${themedHtml}</body>
    </html>
  `;
}

function exportJson(template: WorkingTemplate | EmailTemplateRecord) {
  const blob = new Blob([JSON.stringify(template, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${"templateName" in template ? template.templateName : template.name}.json`;
  link.click();
  URL.revokeObjectURL(url);
}
// ─── ThemeApplyPanel ─────────────────────────────────────────────────────────
// Shown below the ThemeBuilder in the Theme tab.
// Lets admin select individual templates, preview them with the active theme,
// and apply the CSS to each one.

function ThemeApplyPanel({
  templates,
  settings,
  sampleValues,
  applying,
  onApply,
  onPreview,
}: {
  templates: EmailTemplateRecord[];
  settings: ThemeSettings;
  sampleValues: Record<string, string | undefined>;
  applying: boolean;
  onApply: (selected: EmailTemplateRecord[]) => void;
  onPreview: (template: EmailTemplateRecord) => void;
}) {
  const [selected, setSelected] = useState<Set<number | string>>(new Set());

  const toggle = (id: number | string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (selected.size === templates.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(templates.map((t) => t.id ?? t.name)));
    }
  };

  const selectedTemplates = templates.filter((t) => selected.has(t.id ?? t.name));

  if (templates.length === 0) return null;

  return (
    <div className="mt-5 rounded-2xl border border-border bg-card p-5 shadow-sm space-y-4">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="flex items-center gap-2 text-sm font-bold text-foreground">
            <PaintBucket className="h-4 w-4 text-primary" />
            Apply &quot;{settings.themeName}&quot; to Email Templates
          </h3>
          <p className="mt-0.5 text-[11px] text-muted-foreground">
            Select templates to render their HTML with this theme&apos;s CSS. Saved templates will display the themed preview.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={toggleAll}
            className="inline-flex items-center gap-1.5 rounded-xl border border-border px-3 py-1.5 text-xs font-bold text-foreground hover:bg-input cursor-pointer transition-all"
          >
            {selected.size === templates.length ? <SquareCheck className="h-4 w-4 text-primary" /> : <Square className="h-4 w-4" />}
            {selected.size === templates.length ? "Deselect All" : "Select All"}
          </button>
          <button
            type="button"
            disabled={selected.size === 0 || applying}
            onClick={() => onApply(selectedTemplates)}
            className="inline-flex items-center gap-1.5 rounded-xl bg-primary px-4 py-1.5 text-xs font-bold text-white hover:bg-primary/90 disabled:opacity-60 cursor-pointer transition-all"
          >
            {applying
              ? <RefreshCw className="h-4 w-4 animate-spin" />
              : <Check className="h-4 w-4" />}
            Apply to {selected.size > 0 ? `${selected.size} Template${selected.size > 1 ? "s" : ""}` : "Selected"}
          </button>
        </div>
      </div>

      {/* Template grid */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
        {templates.map((template) => {
          const key = template.id ?? template.name;
          const isSelected = selected.has(key);
          const alreadyUsesTheme = template.themeName === settings.themeName;
          const previewDoc = themedPreviewDocument(template.html, template.css ?? "", settings, sampleValues);

          return (
            <div
              key={key}
              onClick={() => toggle(key)}
              className={`group relative cursor-pointer rounded-2xl border-2 bg-background p-3 transition-all ${
                isSelected ? "border-primary shadow-md shadow-primary/10" : "border-border hover:border-primary/30"
              }`}
            >
              {/* Checkbox top-left */}
              <div className={`absolute left-3 top-3 z-10 rounded-md p-0.5 ${isSelected ? "text-primary" : "text-muted-foreground"}`}>
                {isSelected ? <SquareCheck className="h-4 w-4" /> : <Square className="h-4 w-4" />}
              </div>

              {/* Already themed badge */}
              {alreadyUsesTheme && (
                <div className="absolute right-3 top-3 z-10 flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-bold text-emerald-600 dark:text-emerald-400">
                  <Check className="h-3 w-3" />
                  Applied
                </div>
              )}

              {/* Mini themed preview iframe */}
              <div className="h-32 overflow-hidden rounded-xl border border-border bg-slate-100 mb-2.5">
                <iframe
                  title={`${template.name} preview`}
                  srcDoc={previewDoc}
                  sandbox="allow-same-origin"
                  className="h-[400px] w-[300%] origin-top-left scale-[0.333] border-0 pointer-events-none"
                />
              </div>

              {/* Template info */}
              <div className="space-y-1 pl-6">
                <p className="truncate text-xs font-bold text-foreground">{template.name}</p>
                <p className="truncate text-[10px] text-muted-foreground">{template.subject || "No subject"}</p>
                <div className="flex items-center gap-1.5 flex-wrap">
                  <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold text-muted-foreground">{template.status}</span>
                  {template.themeName && (
                    <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-bold text-primary truncate max-w-[8rem]">{template.themeName}</span>
                  )}
                </div>
              </div>

              {/* Preview button */}
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); onPreview(template); }}
                className="mt-2.5 w-full inline-flex items-center justify-center gap-1.5 rounded-xl border border-border px-2 py-1.5 text-[11px] font-bold text-foreground hover:bg-primary/5 hover:border-primary/30 cursor-pointer transition-all"
              >
                <Eye className="h-3.5 w-3.5 text-primary" />
                Preview with Theme
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export function EmailTemplateBuilder() {
  const { user } = useAuth();
  const [viewMode, setViewMode] = useState<ViewMode>("manager");
  const [activeSection, setActiveSection] = useState<PlatformSection>("templates");
  const [communities, setCommunities] = useState<CommunityResponse[]>([]);
  const [communityId, setCommunityId] = useState<number | null>(user?.communityId ?? null);
  const [templates, setTemplates] = useState<EmailTemplateRecord[]>([]);
  const [workingTemplate, setWorkingTemplate] = useState<WorkingTemplate | null>(null);
  const [editor, setEditor] = useState<Editor | null>(null);
  const [device, setDevice] = useState<PreviewDevice>("desktop");
  const [previewDevice, setPreviewDevice] = useState<PreviewDevice>("desktop");
  const [previewTheme, setPreviewTheme] = useState<PreviewTheme>("light");
  const [previewOpen, setPreviewOpen] = useState(false);
  const [savedPreviewTemplate, setSavedPreviewTemplate] = useState<EmailTemplateRecord | null>(null);
  const [selectedSampleId, setSelectedSampleId] = useState(sampleDatasets[0].id);
  const [selectedClient, setSelectedClient] = useState(emailClients[0]);
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [testRecipient, setTestRecipient] = useState(user?.email ?? "");
  const [scheduleMode, setScheduleMode] = useState("Send Now");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState("");
  const [savedThemes, setSavedThemes] = useState<EmailThemeRecord[]>([]);
  const [themesLoading, setThemesLoading] = useState(false);
  const [activeThemeSettings, setActiveThemeSettings] = useState<ThemeSettings>(DEFAULT_THEME);
  const [themePreviewTemplate, setThemePreviewTemplate] = useState<EmailTemplateRecord | null>(null);

  useEffect(() => {
    async function loadCommunities() {
      try {
        const list = await communityService.getCommunities();
        setCommunities(list);
        setCommunityId((prev) => prev ?? user?.communityId ?? list[0]?.id ?? null);
      } catch {
        showError("Failed to load communities");
      }
    }
    void loadCommunities();
  }, [user?.communityId]);

  const loadTemplates = useCallback(async () => {
    if (communityId == null) return;
    setLoading(true);
    try {
      const result = await emailTemplateService.list(communityId);
      setTemplates(result);
    } catch {
      setTemplates([]);
      showWarning("Email template API is not available yet. You can still compose a new template.");
    } finally {
      setLoading(false);
    }
  }, [communityId]);

  useEffect(() => {
    void loadTemplates();
  }, [loadTemplates]);

  const loadSavedThemes = useCallback(async () => {
    if (communityId == null) return;
    setThemesLoading(true);
    try {
      const list = await themePersistenceService.list(communityId);
      setSavedThemes(list);
      const preferredTheme = parseThemeRecord(list.find((theme) => theme.isDefault) ?? list[0]);
      if (preferredTheme) {
        setActiveThemeSettings(preferredTheme);
      }
    } catch {
      setSavedThemes([]);
      setActiveThemeSettings(DEFAULT_THEME);
    } finally {
      setThemesLoading(false);
    }
  }, [communityId]);

  useEffect(() => {
    void loadSavedThemes();
  }, [loadSavedThemes]);

  const filteredCommunities = useMemo(() => {
    if (!user?.communityId) return communities;
    return communities.filter((c) => c.id === user.communityId);
  }, [communities, user?.communityId]);

  const filteredTemplates = useMemo(() => {
    const term = search.trim().toLowerCase();
    return templates.filter((template) => {
      const categoryMatch = selectedCategory === "All" || template.category === selectedCategory;
      const termMatch = !term || `${template.name} ${template.subject} ${template.status} ${template.category ?? ""} ${(template.tags ?? []).join(" ")}`.toLowerCase().includes(term);
      return categoryMatch && termMatch;
    });
  }, [templates, search, selectedCategory]);

  const selectedSample = sampleDatasets.find((sample) => sample.id === selectedSampleId) ?? sampleDatasets[0];
  const savedPreviewThemeSettings = parseThemeJson(savedPreviewTemplate?.themeJson) ?? activeThemeSettings;
  const savedPreviewHtml = savedPreviewTemplate
    ? replaceMergeFields(savedPreviewTemplate.html || starterTemplateHtml, selectedSample.values)
    : "";

  const openBuilder = (template: WorkingTemplate) => {
    setEditor(null);
    setWorkingTemplate(buildAppliedThemeTemplate(template, activeThemeSettings));
    setViewMode("builder");
  };

  const handleSnapshotChange = useCallback((snapshot: { html: string; css: string; jsonLayout: unknown }) => {
    setWorkingTemplate((current) => current ? { ...current, ...snapshot } : current);
  }, []);

  const insertBlock = (block: (typeof emailBlocks)[number]) => {
    editor?.addComponents(block.content);
  };

  const insertField = (token: string) => {
    editor?.runCommand("insert-dynamic-field", { token });
  };

  const saveTemplate = async (status?: EmailTemplateStatus) => {
    if (!workingTemplate) return;
    if (!workingTemplate.templateName.trim()) {
      showError("Template name is required");
      return;
    }
    if (!workingTemplate.subject.trim()) {
      showError("Subject is required");
      return;
    }

    setSaving(true);
    try {
      const payload = buildAppliedThemeTemplate(
        { ...workingTemplate, status: status ?? workingTemplate.status },
        activeThemeSettings
      );
      const saved = await emailTemplateService.save(payload);
      showSuccess(status === "REVIEW" ? "Template submitted for review" : "Email template saved");
      setTemplates((current) => {
        const withoutOld = current.filter((template) => template.id !== saved.id);
        return [saved, ...withoutOld];
      });
      setWorkingTemplate(toWorkingTemplate(saved, workingTemplate.communityId));
    } catch (err: any) {
      showError(err?.message || "Failed to save email template");
    } finally {
      setSaving(false);
    }
  };

  const deleteTemplate = async (template: EmailTemplateRecord) => {
    if (!template.id) return;
    try {
      await emailTemplateService.delete(template.id);
      setTemplates((current) => current.filter((item) => item.id !== template.id));
      showSuccess("Email template deleted");
    } catch {
      showError("Failed to delete email template");
    }
  };

  const applyThemeToTemplates = async (settings = activeThemeSettings, targetTemplates = filteredTemplates) => {
    if (targetTemplates.length === 0) {
      showWarning("No templates to update");
      return;
    }

    setSaving(true);
    try {
      const updated = await Promise.all(
        targetTemplates.map((template) => {
          const working = buildAppliedThemeTemplate(toWorkingTemplate(template, communityId ?? 0), settings);
          return emailTemplateService.save(working);
        })
      );
      setTemplates((current) => {
        const updatedById = new Map(updated.map((template) => [template.id, template]));
        return current.map((template) => updatedById.get(template.id) ?? template);
      });
      showSuccess(`${settings.themeName} applied to ${updated.length} template${updated.length === 1 ? "" : "s"}`);
    } catch (err: any) {
      showError(err?.message || "Failed to apply theme to templates");
    } finally {
      setSaving(false);
    }
  };

  const uploadImage = async (file: File, selectedCommunityId: number) => {
    const result = await emailTemplateService.uploadAsset(file, selectedCommunityId);
    showSuccess("Image uploaded");
    return result.url;
  };

  const sendTest = () => {
    if (!testRecipient.trim()) {
      showError("Enter a test recipient");
      return;
    }
    showSuccess(`Test prepared for ${testRecipient}`);
  };

  if (communityId == null) {
    return (
      <div className="rounded-2xl border border-border bg-card p-8 text-center shadow-sm">
        <Mail className="mx-auto h-10 w-10 text-muted-foreground/40" />
        <h2 className="mt-3 text-lg font-bold text-foreground">Email Campaign Manager</h2>
        <p className="mt-1 text-sm text-muted-foreground">Select a community before creating templates.</p>
      </div>
    );
  }

  if (viewMode === "builder" && workingTemplate) {
    const previewHtml = replaceMergeFields(workingTemplate.html, selectedSample.values);

    return (
      <div className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <button
            type="button"
            onClick={() => setViewMode("manager")}
            className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-xs font-bold text-foreground hover:bg-input cursor-pointer transition-all"
          >
            <ArrowLeft className="h-4 w-4" />
            Manager
          </button>
          <div className="text-right">
            <h2 className="text-xl font-bold text-foreground">{workingTemplate.templateName}</h2>
            <p className="text-xs text-muted-foreground">{workingTemplate.subject} · {workingTemplate.category} · {workingTemplate.status}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-3 xl:grid-cols-[minmax(0,1fr)_24rem]">
          <Toolbar
            device={device}
            saving={saving}
            onDeviceChange={setDevice}
            onPreview={() => setPreviewOpen(true)}
            onSave={() => void saveTemplate()}
          />
          <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-border bg-card px-4 py-3 shadow-sm">
            <select value={selectedSampleId} onChange={(event) => setSelectedSampleId(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none">
              {sampleDatasets.map((sample) => <option key={sample.id} value={sample.id}>{sample.label}</option>)}
            </select>
            <select value={selectedClient} onChange={(event) => setSelectedClient(event.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none">
              {emailClients.map((client) => <option key={client}>{client}</option>)}
            </select>
            <button type="button" onClick={() => void saveTemplate("REVIEW")} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-bold text-foreground hover:bg-input cursor-pointer">
              <CheckCircle2 className="h-4 w-4" />
              Review
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 xl:grid-cols-[16rem_minmax(0,1fr)_20rem]">
          <ComponentPalette blocks={emailBlocks} onInsertBlock={insertBlock} />
          <BuilderCanvas
            key={workingTemplate.id ?? `${workingTemplate.templateName}-${workingTemplate.communityId}`}
            html={workingTemplate.html}
            css={workingTemplate.css}
            device={device}
            onReady={setEditor}
            onChange={handleSnapshotChange}
          />
          <PropertyPanel
            editor={editor}
            communityId={communityId}
            templateName={workingTemplate.templateName}
            subject={workingTemplate.subject}
            savedThemes={savedThemes}
            activeThemeName={activeThemeSettings.themeName}
            onTemplateNameChange={(templateName) => setWorkingTemplate((current) => current ? { ...current, templateName } : current)}
            onSubjectChange={(subject) => setWorkingTemplate((current) => current ? { ...current, subject } : current)}
            onInsertField={insertField}
            onUploadImage={uploadImage}
            onThemeApplied={(settings) => {
              setActiveThemeSettings(settings);
              setWorkingTemplate((current) => current ? buildAppliedThemeTemplate(current, settings) : current);
            }}
          />
        </div>

        <PreviewModal
          open={previewOpen}
          html={previewHtml}
          css={stripThemeCss(workingTemplate.css)}
          device={previewDevice}
          theme={previewTheme}
          themeSettings={activeThemeSettings}
          onDeviceChange={setPreviewDevice}
          onThemeChange={setPreviewTheme}
          onClose={() => setPreviewOpen(false)}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10">
              <Mail className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">Enterprise Email Campaign Manager</h2>
              <p className="text-xs text-muted-foreground">Templates, themes, blocks, approvals, delivery checks, analytics, and audit history</p>
            </div>
          </div>

          <div className="flex flex-col gap-2 sm:flex-row">
            <select
              value={communityId ?? ""}
              onChange={(event) => setCommunityId(Number(event.target.value))}
              disabled={!!user?.communityId}
              className="rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none disabled:cursor-not-allowed disabled:opacity-70"
            >
              {filteredCommunities.map((community) => (
                <option key={community.id} value={community.id}>{community.name}</option>
              ))}
            </select>
            <button
              type="button"
              onClick={() => openBuilder(createBlankTemplate(communityId))}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-bold text-white hover:bg-primary/90 cursor-pointer transition-all"
            >
              <Plus className="h-4 w-4" />
              New Template
            </button>
          </div>
        </div>

        <div className="mt-5 flex gap-1 overflow-x-auto">
          {platformSections.map((section) => {
            const Icon = section.icon;
            const active = activeSection === section.id;
            return (
              <button
                key={section.id}
                type="button"
                onClick={() => setActiveSection(section.id)}
                className={`inline-flex items-center gap-2 whitespace-nowrap rounded-xl px-3.5 py-2 text-xs font-bold transition-all cursor-pointer ${active ? "bg-primary text-white" : "text-muted-foreground hover:bg-input hover:text-foreground"}`}
              >
                <Icon className="h-4 w-4" />
                {section.label}
              </button>
            );
          })}
        </div>
      </div>

      {activeSection === "templates" && (
        <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]">
          <div className="space-y-4">
            <div className="grid grid-cols-1 gap-3 md:grid-cols-5">
              {emailTemplateCategories.map((category) => (
                <button
                  key={category.id}
                  type="button"
                  onClick={() => setSelectedCategory(category.module)}
                  className="rounded-2xl border border-border bg-card p-4 text-left shadow-sm hover:border-primary/35 cursor-pointer transition-all"
                >
                  <span className="block h-1.5 w-10 rounded-full" style={{ background: category.color }} />
                  <span className="mt-3 block text-sm font-bold text-foreground">{category.module}</span>
                  <span className="mt-1 block text-[11px] text-muted-foreground">{category.items.join(", ")}</span>
                </button>
              ))}
            </div>

            <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card px-4 py-3 shadow-sm md:flex-row md:items-center">
              <div className="flex min-w-0 flex-1 items-center gap-3">
                <Search className="h-4 w-4 text-muted-foreground" />
                <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by category, community, status, creator, or tag..." className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground" />
              </div>
              <select value={selectedCategory} onChange={(event) => setSelectedCategory(event.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none">
                <option>All</option>
                {emailTemplateCategories.map((category) => <option key={category.id}>{category.module}</option>)}
              </select>
              <button type="button" onClick={() => void loadTemplates()} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-bold text-foreground hover:bg-input cursor-pointer">
                <RefreshCw className="h-4 w-4" />
                Refresh
              </button>
              <button type="button" onClick={() => void applyThemeToTemplates()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-bold text-white hover:bg-primary/90 disabled:opacity-60 cursor-pointer">
                <PaintBucket className="h-4 w-4" />
                Apply Theme
              </button>
            </div>

            {loading ? (
              <div className="flex items-center justify-center rounded-2xl border border-border bg-card py-16 text-sm text-muted-foreground">
                <RefreshCw className="mr-2 h-4 w-4 animate-spin text-primary" />
                Loading templates...
              </div>
            ) : filteredTemplates.length > 0 ? (
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                {filteredTemplates.map((template) => (
                  <TemplateCard
                    key={template.id ?? template.name}
                    template={template}
                    communityId={communityId}
                    themeSettings={activeThemeSettings}
                    sampleValues={selectedSample.values}
                    onEdit={() => openBuilder(toWorkingTemplate(template, communityId))}
                    onPreview={() => setSavedPreviewTemplate(template)}
                    onClone={() => openBuilder(createBlankTemplate(communityId, `${template.name} Copy`, template.category ?? "Community"))}
                    onExport={() => exportJson(template)}
                    onDelete={() => void deleteTemplate(template)}
                  />
                ))}
              </div>
            ) : (
              <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center">
                <Mail className="mx-auto h-10 w-10 text-muted-foreground/40" />
                <h3 className="mt-3 text-base font-bold text-foreground">No saved templates yet</h3>
                <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">Start with a reusable tournament, invoice, OTP, or newsletter layout and move it through review and publishing.</p>
                <button type="button" onClick={() => openBuilder(createBlankTemplate(communityId))} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-bold text-white hover:bg-primary/90 cursor-pointer">
                  <Plus className="h-4 w-4" />
                  Create Template
                </button>
              </div>
            )}
          </div>

          <aside className="space-y-4">
            <Panel title="Quick Starters" icon={FolderOpen}>
              <div className="space-y-2">
                {templateStarters.map((starter) => (
                  <button key={starter.name} type="button" onClick={() => openBuilder(createBlankTemplate(communityId, starter.name, starter.category))} className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-left text-xs font-semibold text-foreground hover:border-primary/35 hover:bg-primary/5 cursor-pointer">
                    <span className="block">{starter.name}</span>
                    <span className="mt-0.5 block text-[10px] text-muted-foreground">{starter.category} · {starter.tags.join(", ")}</span>
                  </button>
                ))}
              </div>
            </Panel>

            <Panel title="Preview & Send" icon={TestTube2}>
              <div className="space-y-2">
                <select value={selectedSampleId} onChange={(event) => setSelectedSampleId(event.target.value)} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none">
                  {sampleDatasets.map((sample) => <option key={sample.id} value={sample.id}>{sample.label}</option>)}
                </select>
                <input value={testRecipient} onChange={(event) => setTestRecipient(event.target.value)} placeholder="admin@gmail.com" className="w-full rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none" />
                <select value={scheduleMode} onChange={(event) => setScheduleMode(event.target.value)} className="w-full rounded-xl border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground outline-none">
                  {["Send Now", "Tomorrow", "Next Week", "Specific Date", "Recurring Newsletter"].map((mode) => <option key={mode}>{mode}</option>)}
                </select>
                <button type="button" onClick={sendTest} className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-foreground px-3 py-2 text-xs font-bold text-background hover:opacity-90 cursor-pointer">
                  <Send className="h-4 w-4" />
                  Send Test
                </button>
              </div>
            </Panel>
          </aside>
        </div>
      )}

      <PreviewModal
        open={!!savedPreviewTemplate}
        html={savedPreviewHtml}
        css={stripThemeCss(savedPreviewTemplate?.css ?? "")}
        device={previewDevice}
        theme={previewTheme}
        themeSettings={savedPreviewThemeSettings}
        onDeviceChange={setPreviewDevice}
        onThemeChange={setPreviewTheme}
        onClose={() => setSavedPreviewTemplate(null)}
      />

      {activeSection === "theme" && (
        <div>
          {communityId != null ? (
            <>
              <ThemeBuilder
                communityId={communityId}
                initialSettings={activeThemeSettings}
                savedThemes={savedThemes}
                onThemeSaved={(settings) => {
                  setActiveThemeSettings(settings);
                  void loadSavedThemes();
                }}
                onThemeSelected={setActiveThemeSettings}
              />
              <ThemeApplyPanel
                templates={templates}
                settings={activeThemeSettings}
                sampleValues={selectedSample.values}
                applying={saving}
                onApply={(selected) => void applyThemeToTemplates(activeThemeSettings, selected)}
                onPreview={(template) => setThemePreviewTemplate(template)}
              />
              <PreviewModal
                open={!!themePreviewTemplate}
                html={themePreviewTemplate
                  ? replaceMergeFields(themePreviewTemplate.html || starterTemplateHtml, selectedSample.values)
                  : ""}
                css={stripThemeCss(themePreviewTemplate?.css ?? "")}
                device={previewDevice}
                theme={previewTheme}
                themeSettings={activeThemeSettings}
                onDeviceChange={setPreviewDevice}
                onThemeChange={setPreviewTheme}
                onClose={() => setThemePreviewTemplate(null)}
              />
            </>
          ) : (
            <div className="flex items-center justify-center rounded-2xl border border-border bg-card py-16 text-sm text-muted-foreground">
              {themesLoading ? "Loading themes..." : "Select a community to manage themes"}
            </div>
          )}
        </div>
      )}

      {activeSection === "blocks" && (
        <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
          <Panel title="Reusable Block Library" icon={Layers}>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              {emailBlocks.map((block) => {
                const Icon = block.icon;
                return (
                  <div key={block.id} className="rounded-2xl border border-border bg-background p-4">
                    <Icon className="h-5 w-5 text-primary" />
                    <h3 className="mt-3 text-sm font-bold text-foreground">{block.label}</h3>
                    <p className="mt-1 text-xs text-muted-foreground">{block.category} reusable section · mapped across templates</p>
                  </div>
                );
              })}
            </div>
          </Panel>
          <div className="space-y-5">
            <Panel title="Conditional Content" icon={Workflow}>
              <div className="space-y-2">
                {conditionalRules.map((rule) => <div key={rule} className="rounded-xl border border-border bg-background px-3 py-2 text-xs text-foreground">{rule}</div>)}
              </div>
            </Panel>
            <Panel title="Repeatable Collections" icon={Copy}>
              <div className="flex flex-wrap gap-2">
                {repeatableCollections.map((item) => <span key={item} className="rounded-full bg-primary/10 px-3 py-1 text-[11px] font-bold text-primary">{item}</span>)}
              </div>
            </Panel>
          </div>
        </div>
      )}

      {activeSection === "assets" && (
        <Panel title="Image Library" icon={ImageIcon}>
          <div className="mb-4 flex flex-col gap-3 md:flex-row">
            <div className="flex min-w-0 flex-1 items-center gap-3 rounded-xl border border-border bg-background px-3 py-2">
              <Search className="h-4 w-4 text-muted-foreground" />
              <input placeholder="Search banners, logos, sponsors, icons, QR codes..." className="min-w-0 flex-1 bg-transparent text-sm outline-none" />
            </div>
            <button type="button" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-2 text-xs font-bold text-foreground hover:bg-input cursor-pointer">
              <Upload className="h-4 w-4" />
              Upload Asset
            </button>
          </div>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
            {imageLibraryAssets.map((asset) => (
              <div key={asset.name} className="rounded-2xl border border-border bg-background p-4">
                <div className="flex h-28 items-center justify-center rounded-xl bg-muted">
                  <ImageIcon className="h-8 w-8 text-muted-foreground" />
                </div>
                <h3 className="mt-3 text-sm font-bold text-foreground">{asset.name}</h3>
                <p className="text-xs text-muted-foreground">{asset.folder} · {asset.type}</p>
                <p className="mt-2 text-[10px] font-semibold text-primary">{asset.tags.join(", ")}</p>
              </div>
            ))}
          </div>
        </Panel>
      )}

      {activeSection === "workflow" && (
        <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
          <Panel title="Approval Workflow" icon={Workflow}>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-5">
              {approvalSteps.map((step, index) => (
                <div key={step} className="rounded-2xl border border-border bg-background p-4">
                  <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-black text-white">{index + 1}</div>
                  <h3 className="mt-3 text-sm font-bold text-foreground">{step}</h3>
                  <p className="mt-1 text-xs text-muted-foreground">Version gate and audit checkpoint</p>
                </div>
              ))}
            </div>
          </Panel>
          <Panel title="Version History" icon={History}>
            <div className="space-y-3">
              {["V4 Published", "V3 Approved", "V2 Review", "V1 Draft"].map((version) => (
                <div key={version} className="flex items-center justify-between rounded-xl border border-border bg-background px-3 py-2">
                  <span className="text-xs font-bold text-foreground">{version}</span>
                  <button type="button" className="text-[11px] font-bold text-primary">Rollback</button>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      )}

      {activeSection === "analytics" && (
        <Panel title="Email Analytics" icon={BarChart3}>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4 xl:grid-cols-8">
            {analyticsMetrics.map((metric) => (
              <div key={metric.label} className="rounded-2xl border border-border bg-background p-4">
                <p className="text-2xl font-black text-foreground">{metric.value}</p>
                <p className="mt-1 text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{metric.label}</p>
              </div>
            ))}
          </div>
          <div className="mt-5 grid grid-cols-1 gap-4 xl:grid-cols-2">
            <Panel title="Client Compatibility" icon={Eye}>
              <div className="grid grid-cols-2 gap-2">
                {emailClients.map((client) => <div key={client} className="rounded-xl border border-border bg-background px-3 py-2 text-xs font-bold text-foreground">{client}</div>)}
              </div>
            </Panel>
            <Panel title="Scheduling" icon={CalendarClock}>
              <div className="grid grid-cols-2 gap-2">
                {["Send Now", "Tomorrow", "Next Week", "Specific Date", "Recurring Newsletter"].map((item) => <div key={item} className="rounded-xl border border-border bg-background px-3 py-2 text-xs font-bold text-foreground">{item}</div>)}
              </div>
            </Panel>
          </div>
        </Panel>
      )}

      {activeSection === "governance" && (
        <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">
          <Panel title="Permissions" icon={LockKeyhole}>
            <div className="space-y-3">
              {permissionMatrix.map((row) => (
                <div key={row.role} className="rounded-xl border border-border bg-background p-3">
                  <h3 className="text-sm font-bold text-foreground">{row.role}</h3>
                  <p className="mt-1 text-xs text-muted-foreground">{row.access}</p>
                </div>
              ))}
            </div>
          </Panel>
          <Panel title="Audit Log" icon={Activity}>
            <div className="space-y-3">
              {auditEvents.map((event) => (
                <div key={`${event.user}-${event.date}`} className="rounded-xl border border-border bg-background p-3">
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="text-sm font-bold text-foreground">{event.action}</h3>
                    <span className="text-[10px] font-black text-primary">{event.version}</span>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{event.user} · {event.date}</p>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      )}
    </div>
  );
}

function Panel({ title, icon: Icon, children }: { title: string; icon: React.ElementType; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
      <div className="mb-4 flex items-center gap-2">
        <Icon className="h-4 w-4 text-primary" />
        <h3 className="text-sm font-bold text-foreground">{title}</h3>
      </div>
      {children}
    </section>
  );
}

function TemplateCard({
  template,
  themeSettings,
  sampleValues,
  onEdit,
  onPreview,
  onClone,
  onExport,
  onDelete,
}: {
  template: EmailTemplateRecord;
  communityId: number;
  themeSettings: ThemeSettings;
  sampleValues: Record<string, string | undefined>;
  onEdit: () => void;
  onPreview: () => void;
  onClone: () => void;
  onExport: () => void;
  onDelete: () => void;
}) {
  const statusIcon = template.status === "PUBLISHED" || template.status === "ACTIVE" ? CheckCircle2 : template.status === "ARCHIVED" ? Archive : Clock3;
  const StatusIcon = statusIcon;
  const templateThemeSettings = parseThemeJson(template.themeJson) ?? themeSettings;
  const previewDoc = themedPreviewDocument(template.html, template.css ?? "", templateThemeSettings, sampleValues);
  const displayedThemeName = template.themeName ?? templateThemeSettings.themeName;

  return (
    <div className="group rounded-2xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/35 hover:shadow-md">
      <div className="mb-4 overflow-hidden rounded-xl border border-border bg-muted">
        <div className="flex items-center justify-between border-b border-border bg-background px-3 py-2">
          <span className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">Saved Preview</span>
          <span className="truncate text-[10px] font-bold text-primary">{displayedThemeName}</span>
        </div>
        <div className="h-40 overflow-hidden bg-slate-100">
          <iframe
            title={`${template.name} saved template preview`}
            srcDoc={previewDoc}
            sandbox="allow-same-origin"
            className="h-[480px] w-[300%] origin-top-left scale-[0.333] border-0 bg-white"
          />
        </div>
      </div>

      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Layers className="h-4 w-4 text-primary shrink-0" />
            <h3 className="truncate text-sm font-bold text-foreground">{template.name}</h3>
          </div>
          <p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{template.subject || "No subject configured"}</p>
        </div>
        <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-black uppercase text-primary">
          <StatusIcon className="h-3 w-3" />
          {template.status}
        </span>
      </div>

      <div className="mt-3 flex flex-wrap gap-1.5">
        <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-bold text-muted-foreground">{template.category ?? "Community"}</span>
        <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-bold text-primary">{displayedThemeName}</span>
        {(template.tags ?? []).slice(0, 3).map((tag) => (
          <span key={tag} className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-bold text-muted-foreground">{tag}</span>
        ))}
      </div>


      <div className="mt-4 flex items-center justify-between gap-2 border-t border-border pt-3">
        <span className="text-[11px] text-muted-foreground">v{template.version ?? 1}</span>
        <div className="flex items-center gap-1.5">
          <button type="button" title="Preview template" onClick={onPreview} className="h-8 w-8 rounded-lg text-muted-foreground hover:bg-primary/10 hover:text-primary flex items-center justify-center cursor-pointer">
            <Eye className="h-4 w-4" />
          </button>
          <button type="button" title="Clone template" onClick={onClone} className="h-8 w-8 rounded-lg text-muted-foreground hover:bg-input hover:text-foreground flex items-center justify-center cursor-pointer">
            <Copy className="h-4 w-4" />
          </button>
          <button type="button" title="Export JSON" onClick={onExport} className="h-8 w-8 rounded-lg text-muted-foreground hover:bg-input hover:text-foreground flex items-center justify-center cursor-pointer">
            <Download className="h-4 w-4" />
          </button>
          {template.id && (
            <button type="button" title="Delete template" onClick={onDelete} className="h-8 w-8 rounded-lg text-muted-foreground hover:bg-danger/10 hover:text-danger flex items-center justify-center cursor-pointer">
              <Trash2 className="h-4 w-4" />
            </button>
          )}
          <button type="button" onClick={onEdit} className="rounded-lg bg-foreground px-3 py-2 text-xs font-bold text-background hover:opacity-90 cursor-pointer">
            Edit
          </button>
        </div>
      </div>
    </div>
  );
}
