import type { TeamProfile } from './TeamHubTypes';

export const SAMPLE_TOURNAMENT_TEAMS: TeamProfile[] = [
  {
    id: 1,
    name: 'Phoenix Blasters',
    shortName: 'PB',
    colorHex: '#ea580c', // Bright Orange
    secondaryColor: '#f97316',
    emoji: '🔥',
    ownerName: 'Vikram & Meera Reddy',
    ownerCompany: 'Viseshta Infra',
    captainName: 'Rohit Sharma (Block B-402)',
    captainConfirmed: true,
    viceCaptainName: 'Arjun Das',
    motto: 'Rising From The Ashes',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 84500,
    remainingBudget: 15500,
    maxSquadSize: 12,
    titlesCount: 2,
    winLossRatio: '14W - 4L',
    squad: [
      {
        id: 'pb-1',
        name: 'Rohit Sharma',
        role: 'BATSMAN',
        category: 'Icon',
        jerseyNumber: 45,
        acquiredPrice: 24000,
        status: 'CAPTAIN',
        flatNumber: 'B-402',
        isCommunityResident: true,
        stats: { matches: 18, runs: 642, strikeRate: 158.4, highestScore: '94*' },
      },
      {
        id: 'pb-2',
        name: 'Arjun Das',
        role: 'ALL_ROUNDER',
        category: 'Gold',
        jerseyNumber: 7,
        acquiredPrice: 18500,
        status: 'VICE_CAPTAIN',
        flatNumber: 'A-108',
        isCommunityResident: true,
        stats: { matches: 16, runs: 310, wickets: 19, strikeRate: 142.0, economy: 6.8 },
      },
      {
        id: 'pb-3',
        name: 'Karthik Varma',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 23,
        acquiredPrice: 14000,
        status: 'AUCTION_BUY',
        flatNumber: 'C-701',
        isCommunityResident: true,
        stats: { matches: 15, wickets: 24, economy: 6.2, bestBowling: '4/14' },
      },
      {
        id: 'pb-4',
        name: 'Aditya Sen',
        role: 'WICKET_KEEPER',
        category: 'Silver',
        jerseyNumber: 18,
        acquiredPrice: 11000,
        status: 'AUCTION_BUY',
        flatNumber: 'D-203',
        isCommunityResident: true,
        stats: { matches: 12, runs: 245, strikeRate: 136.5 },
      },
      {
        id: 'pb-5',
        name: 'Naveen Kumar',
        role: 'BOWLER',
        category: 'Silver',
        jerseyNumber: 99,
        acquiredPrice: 9000,
        status: 'AUCTION_BUY',
        flatNumber: 'A-504',
        isCommunityResident: true,
        stats: { matches: 14, wickets: 16, economy: 7.4 },
      },
      {
        id: 'pb-6',
        name: 'Sameer Khan',
        role: 'BATSMAN',
        category: 'Bronze',
        jerseyNumber: 12,
        acquiredPrice: 8000,
        status: 'DRAFT',
        flatNumber: 'B-101',
        isCommunityResident: true,
        stats: { matches: 8, runs: 160, strikeRate: 124.0 },
      },
    ],
  },
  {
    id: 2,
    name: 'Titan Warriors',
    shortName: 'TW',
    colorHex: '#2563eb', // Royal Blue
    secondaryColor: '#3b82f6',
    emoji: '⚔️',
    ownerName: 'Dr. Suresh Chandra',
    ownerCompany: 'Apex Health Partners',
    captainName: 'Vivek Singhania (Villa 42)',
    captainConfirmed: true,
    viceCaptainName: 'Pranav Joshi',
    motto: 'Strength Through Unity',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 91000,
    remainingBudget: 9000,
    maxSquadSize: 12,
    titlesCount: 1,
    winLossRatio: '11W - 7L',
    squad: [
      {
        id: 'tw-1',
        name: 'Vivek Singhania',
        role: 'ALL_ROUNDER',
        category: 'Icon',
        jerseyNumber: 10,
        acquiredPrice: 26000,
        status: 'CAPTAIN',
        flatNumber: 'Villa 42',
        isCommunityResident: true,
        stats: { matches: 20, runs: 512, wickets: 22, strikeRate: 148.2, economy: 7.1 },
      },
      {
        id: 'tw-2',
        name: 'Pranav Joshi',
        role: 'BATSMAN',
        category: 'Gold',
        jerseyNumber: 33,
        acquiredPrice: 19000,
        status: 'VICE_CAPTAIN',
        flatNumber: 'C-304',
        isCommunityResident: true,
        stats: { matches: 18, runs: 430, strikeRate: 139.4, highestScore: '81' },
      },
      {
        id: 'tw-3',
        name: 'Harish Nair',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 8,
        acquiredPrice: 17500,
        status: 'AUCTION_BUY',
        flatNumber: 'D-502',
        isCommunityResident: true,
        stats: { matches: 15, wickets: 21, economy: 6.5, bestBowling: '3/18' },
      },
      {
        id: 'tw-4',
        name: 'Amitabh Roy',
        role: 'WICKET_KEEPER',
        category: 'Silver',
        jerseyNumber: 1,
        acquiredPrice: 14500,
        status: 'AUCTION_BUY',
        flatNumber: 'A-602',
        isCommunityResident: true,
        stats: { matches: 14, runs: 280, strikeRate: 131.0 },
      },
      {
        id: 'tw-5',
        name: 'Devendra Patel',
        role: 'BOWLER',
        category: 'Bronze',
        jerseyNumber: 15,
        acquiredPrice: 14000,
        status: 'DRAFT',
        flatNumber: 'B-305',
        isCommunityResident: true,
        stats: { matches: 10, wickets: 12, economy: 7.8 },
      },
    ],
  },
  {
    id: 3,
    name: 'Falcon Strikers',
    shortName: 'FS',
    colorHex: '#059669', // Emerald Green
    secondaryColor: '#10b981',
    emoji: '🦅',
    ownerName: 'Ramesh & Ananya Gupta',
    ownerCompany: 'Aartah Global',
    captainName: 'Manish Pandey (Block E-201)',
    captainConfirmed: true,
    viceCaptainName: 'Sanjay Rao',
    motto: 'Soar High, Strike Fast',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 78000,
    remainingBudget: 22000,
    maxSquadSize: 12,
    titlesCount: 1,
    winLossRatio: '9W - 5L',
    squad: [
      {
        id: 'fs-1',
        name: 'Manish Pandey',
        role: 'BATSMAN',
        category: 'Icon',
        jerseyNumber: 9,
        acquiredPrice: 22000,
        status: 'CAPTAIN',
        flatNumber: 'E-201',
        isCommunityResident: true,
        stats: { matches: 14, runs: 490, strikeRate: 152.0, highestScore: '88*' },
      },
      {
        id: 'fs-2',
        name: 'Sanjay Rao',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 11,
        acquiredPrice: 18000,
        status: 'VICE_CAPTAIN',
        flatNumber: 'F-102',
        isCommunityResident: true,
        stats: { matches: 14, wickets: 20, economy: 6.1, bestBowling: '4/19' },
      },
      {
        id: 'fs-3',
        name: 'Rahul Hegde',
        role: 'ALL_ROUNDER',
        category: 'Gold',
        jerseyNumber: 27,
        acquiredPrice: 16000,
        status: 'AUCTION_BUY',
        flatNumber: 'A-201',
        isCommunityResident: true,
        stats: { matches: 12, runs: 210, wickets: 14, strikeRate: 140.0 },
      },
      {
        id: 'fs-4',
        name: 'Deepak Chopra',
        role: 'WICKET_KEEPER',
        category: 'Silver',
        jerseyNumber: 77,
        acquiredPrice: 12000,
        status: 'AUCTION_BUY',
        flatNumber: 'B-702',
        isCommunityResident: true,
        stats: { matches: 11, runs: 195, strikeRate: 128.5 },
      },
      {
        id: 'fs-5',
        name: 'Tanmay Bhatia',
        role: 'BATSMAN',
        category: 'Silver',
        jerseyNumber: 14,
        acquiredPrice: 10000,
        status: 'AUCTION_BUY',
        flatNumber: 'C-104',
        isCommunityResident: true,
        stats: { matches: 10, runs: 180, strikeRate: 133.0 },
      },
    ],
  },
  {
    id: 4,
    name: 'Royal Challengers Palm',
    shortName: 'RCP',
    colorHex: '#dc2626', // Crimson Red
    secondaryColor: '#ef4444',
    emoji: '👑',
    ownerName: 'Ashok Varma & Friends',
    ownerCompany: 'Palm Valley Estates',
    captainName: 'Abhishek Mittal (Block D-104)',
    captainConfirmed: true,
    viceCaptainName: 'Gaurav Kulkarni',
    motto: 'Play Bold, Conquer All',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 86000,
    remainingBudget: 14000,
    maxSquadSize: 12,
    titlesCount: 0,
    winLossRatio: '8W - 8L',
    squad: [
      {
        id: 'rcp-1',
        name: 'Abhishek Mittal',
        role: 'ALL_ROUNDER',
        category: 'Icon',
        jerseyNumber: 17,
        acquiredPrice: 25000,
        status: 'CAPTAIN',
        flatNumber: 'D-104',
        isCommunityResident: true,
        stats: { matches: 16, runs: 410, wickets: 18, strikeRate: 155.0, economy: 7.2 },
      },
      {
        id: 'rcp-2',
        name: 'Gaurav Kulkarni',
        role: 'BATSMAN',
        category: 'Gold',
        jerseyNumber: 21,
        acquiredPrice: 20000,
        status: 'VICE_CAPTAIN',
        flatNumber: 'E-401',
        isCommunityResident: true,
        stats: { matches: 15, runs: 375, strikeRate: 141.2, highestScore: '76' },
      },
      {
        id: 'rcp-3',
        name: 'Kishore Kumar',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 90,
        acquiredPrice: 17000,
        status: 'AUCTION_BUY',
        flatNumber: 'B-603',
        isCommunityResident: true,
        stats: { matches: 14, wickets: 19, economy: 6.8 },
      },
      {
        id: 'rcp-4',
        name: 'Yogesh Sharma',
        role: 'BOWLER',
        category: 'Silver',
        jerseyNumber: 5,
        acquiredPrice: 13000,
        status: 'AUCTION_BUY',
        flatNumber: 'C-501',
        isCommunityResident: true,
        stats: { matches: 12, wickets: 14, economy: 7.5 },
      },
      {
        id: 'rcp-5',
        name: 'Sunil Menon',
        role: 'BATSMAN',
        category: 'Silver',
        jerseyNumber: 3,
        acquiredPrice: 11000,
        status: 'DRAFT',
        flatNumber: 'A-302',
        isCommunityResident: true,
        stats: { matches: 9, runs: 150, strikeRate: 120.0 },
      },
    ],
  },
  {
    id: 5,
    name: 'Thunder Bolts',
    shortName: 'TB',
    colorHex: '#7c3aed', // Purple
    secondaryColor: '#8b5cf6',
    emoji: '⚡',
    ownerName: 'Rajesh & Sandeep',
    ownerCompany: 'Monin Sports',
    captainName: 'Anand Ramanathan (Villa 18)',
    captainConfirmed: true,
    viceCaptainName: 'Siddharth Roy',
    motto: 'Lightning In Our Veins',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 80000,
    remainingBudget: 20000,
    maxSquadSize: 12,
    titlesCount: 1,
    winLossRatio: '10W - 6L',
    squad: [
      {
        id: 'tb-1',
        name: 'Anand Ramanathan',
        role: 'BATSMAN',
        category: 'Icon',
        jerseyNumber: 19,
        acquiredPrice: 23000,
        status: 'CAPTAIN',
        flatNumber: 'Villa 18',
        isCommunityResident: true,
        stats: { matches: 16, runs: 520, strikeRate: 160.0, highestScore: '102*' },
      },
      {
        id: 'tb-2',
        name: 'Siddharth Roy',
        role: 'ALL_ROUNDER',
        category: 'Gold',
        jerseyNumber: 88,
        acquiredPrice: 19000,
        status: 'VICE_CAPTAIN',
        flatNumber: 'A-701',
        isCommunityResident: true,
        stats: { matches: 15, runs: 280, wickets: 17, strikeRate: 145.0, economy: 7.0 },
      },
      {
        id: 'tb-3',
        name: 'Tarun Saxena',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 4,
        acquiredPrice: 16000,
        status: 'AUCTION_BUY',
        flatNumber: 'B-204',
        isCommunityResident: true,
        stats: { matches: 14, wickets: 18, economy: 6.4, bestBowling: '3/15' },
      },
      {
        id: 'tb-4',
        name: 'Prakash Rao',
        role: 'WICKET_KEEPER',
        category: 'Silver',
        jerseyNumber: 13,
        acquiredPrice: 12000,
        status: 'AUCTION_BUY',
        flatNumber: 'C-201',
        isCommunityResident: true,
        stats: { matches: 12, runs: 210, strikeRate: 135.0 },
      },
      {
        id: 'tb-5',
        name: 'Nitin Murthy',
        role: 'BOWLER',
        category: 'Bronze',
        jerseyNumber: 6,
        acquiredPrice: 10000,
        status: 'DRAFT',
        flatNumber: 'D-303',
        isCommunityResident: true,
        stats: { matches: 10, wickets: 11, economy: 7.9 },
      },
    ],
  },
  {
    id: 6,
    name: 'Gladiator Knights',
    shortName: 'GK',
    colorHex: '#0891b2', // Cyan / Teal
    secondaryColor: '#06b6d4',
    emoji: '🛡️',
    ownerName: 'Kunal Aggarwal',
    ownerCompany: 'Kotak Community Partner',
    captainName: 'Varun Grover (Block C-102)',
    captainConfirmed: true,
    viceCaptainName: 'Mayank Sethi',
    motto: 'Defend The Glory',
    sportName: 'Cricket',
    tournamentName: 'PHF Premier League',
    season: 'Season 5',
    totalBudget: 100000,
    spentBudget: 88000,
    remainingBudget: 12000,
    maxSquadSize: 12,
    titlesCount: 0,
    winLossRatio: '7W - 9L',
    squad: [
      {
        id: 'gk-1',
        name: 'Varun Grover',
        role: 'ALL_ROUNDER',
        category: 'Icon',
        jerseyNumber: 24,
        acquiredPrice: 24500,
        status: 'CAPTAIN',
        flatNumber: 'C-102',
        isCommunityResident: true,
        stats: { matches: 16, runs: 390, wickets: 20, strikeRate: 142.0, economy: 6.9 },
      },
      {
        id: 'gk-2',
        name: 'Mayank Sethi',
        role: 'BATSMAN',
        category: 'Gold',
        jerseyNumber: 55,
        acquiredPrice: 19500,
        status: 'VICE_CAPTAIN',
        flatNumber: 'E-302',
        isCommunityResident: true,
        stats: { matches: 15, runs: 420, strikeRate: 146.0, highestScore: '85' },
      },
      {
        id: 'gk-3',
        name: 'Girish Iyer',
        role: 'BOWLER',
        category: 'Gold',
        jerseyNumber: 9,
        acquiredPrice: 17000,
        status: 'AUCTION_BUY',
        flatNumber: 'B-501',
        isCommunityResident: true,
        stats: { matches: 14, wickets: 17, economy: 6.6 },
      },
      {
        id: 'gk-4',
        name: 'Omkar Naik',
        role: 'BOWLER',
        category: 'Silver',
        jerseyNumber: 16,
        acquiredPrice: 15000,
        status: 'AUCTION_BUY',
        flatNumber: 'A-404',
        isCommunityResident: true,
        stats: { matches: 11, wickets: 13, economy: 7.2 },
      },
      {
        id: 'gk-5',
        name: 'Chetan Bhagat',
        role: 'BATSMAN',
        category: 'Bronze',
        jerseyNumber: 2,
        acquiredPrice: 12000,
        status: 'DRAFT',
        flatNumber: 'D-401',
        isCommunityResident: true,
        stats: { matches: 8, runs: 120, strikeRate: 115.0 },
      },
    ],
  },
];
